### ISSUE TITLE
schema.org Organization markup

### ISSUE THREAD

**Issue by sourabhmodi60** [WordPress/twentyseventeen#115]
Twentyseventeen is a business-style theme. It will be great if it supports (schema.org)'s Organization markup out of the box?

**Comment by davidakennedy** [comment]
Hey @sourabhmodi60! Thanks for the feature request.

In order to consider this fully, I have some questions:
- It would be helpful to see what an implementation might look like.
- Why the organization schema and not another?
- Do the schemas change much?
- Could this be better accomplished in a plugin or child theme?
- The theme and Core already support Microformats, v1. Why should it support both?

I know a bit about Schema.org, but I am no expert. That said, my take on this right now is:
- This would add a lot of extra markup and make templates harder to understand.
- There seems to be many appropriate schemas for this type of theme. Remember, users will use it for all kinds of sites. So one schema probably doesn't make sense.
- This feels like an edge case that would make changes to templates harder in the future.
- Related: Twenty Fourteen decided not to go Schema.org route: https://core.trac.wordpress.org/ticket/25003

I'm happy to have this discussion though – and especially hear from others more familiar with the subject.

**Comment by ntwb** [comment]
I could get behind Microformats v2....

**Comment by davidakennedy** [comment]
@ntwb Over on Underscores, we've had discussions in the past and currently on Microformats v2. Twenty Seventeen is a different theme with different goals and a different audience, but the conversation is useful for some context: https://github.com/Automattic/_s/search?q=microformats&type=Issues&utf8=%E2%9C%93

I'd have some of the same questions as I listed above.

**Comment by dshanske** [comment]
I would suggest we consider a simple structural implementation of Microformats 2. Basically ensure no styling of microformat elements, implement mf2 elements on some basic structure...so as general as possible.

**Comment by mtomas7** [comment]
I like this Microformats implementation: 

https://github.com/pfefferle/SemPress/blob/master/sempress/inc/semantics.php

I believe it is based on @dshanske work.

It also has the Schema.org function. In my theme I wrapped it in "if ! function_exists" to make it easy to duplicate function in the Child and change tags if needed.

**Comment by dshanske** [comment]
Actually, @pfefferle did SemPress before I started advocating. I iterated on his design.

**Comment by davidakennedy** [comment]
Since I haven't seen a pull request or more details on this issue, I'm going to close it. My questions still stand, and overall, I feel like it would complicate the markup too much for a default theme.

This is a nice use case for a fork or a child theme though.

**Comment by GaryBairead** [comment]
Instead of baking this into a theme, I'd recommend using a plugin that adds schema via JSON-LD

Examples:

https://wordpress.org/plugins/wp-seo-structured-data-schema/
https://wordpress.org/plugins/schema-app-structured-data-for-schemaorg/
https://wordpress.org/plugins/wp-structuring-markup/
