### ISSUE TITLE
Timezone Offset should be set correctly

### ISSUE THREAD

**Issue by dshanske** [WordPress/twentyseventeen#127]
get_the_date( 'c' ) and get_the_modified_date( 'c' ) do not properly show timezone offsets, resulting in incorrectly parsed time. 

'c' should be replaced with DATE_W3C which uses the same but adds the timezone offset for correct parsing.

**Comment by ocean90** [comment]
Technically `c` (which is `Y-m-d\TH:i:sO`) is a valid value for both functions. The issue is that core's `date_i18n()` function doesn't support date shorthands currently, see https://core.trac.wordpress.org/ticket/20973. This prevents adding the [correct timezone data](https://github.com/WordPress/WordPress/blob/30573dc7b20d0b3dffd2399e56f05eb8bc44a4ae/wp-includes/functions.php#L128-L130).

@rarst proposed [a patch](https://core.trac.wordpress.org/attachment/ticket/20973/Unpack_shorthand_date_formats1.patch) which replaces `c` with `DATE_W3C`. It's worth to mention that `DATE_W3C` uses `P` for the timezone (`Y-m-d\TH:i:sP`) so it's not exactly the same but [it doesn't matter](https://www.w3.org/TR/html-markup/datatypes.html#common.data.datetime) in this case.

Core should definitely fix this nasty bug. But in the meantime I think it's fine to use `DATE_W3C` (or `Y-m-d\TH:i:sO`).

**Comment by dshanske** [comment]
Is there an open TRAC ticket for that you know of?

**Comment by dshanske** [comment]
So, do we feel comfortable having this set to 'Y-m-d\TH:i:sO' or 'Y-m-d\TH:i:sP' as opposed to 'c'?

**Comment by Rarst** [comment]
`DATE_W3C` (`Y-m-d\TH:i:sP`) with `P` is correct/identical replacement for `c`, `DATE_ISO8601` (`Y-m-d\TH:i:sO`) is not/different:

> O Difference to Greenwich time (GMT) in hours Example: +0200
> P Difference to Greenwich time (GMT) with colon between hours and minutes (added in PHP 5.1.3)    Example: +02:00
> c ISO 8601 date (added in PHP 5)  2004-02-12T15:19:21+00:00
> 
> http://php.net/manual/en/function.date.php

**Comment by davidakennedy** [comment]
So `DATE_ISO8601` (`Y-m-d\TH:i:sO`)  is the better choice?

**Comment by Rarst** [comment]
> So DATE_ISO8601 (Y-m-d\TH:i:sO) is the better choice?

There is no "better" here really, _both_ are valid for the standard. `DATE_W3C` is just preferable as _exact_ replacement for `c` rather than compatible-but-not-same `DATE_ISO8601`.
