### ISSUE TITLE
Header Image Fails When Front Page is set to Latest Posts

### ISSUE THREAD

**Issue by mrjarbenne** [WordPress/twentyseventeen#132]
I'm seeing an issue with the header image when using the theme with the front page showing latest posts, rather than a single page. The header image doesn't load. When I switch to a static page as the header, the selected header image appears. Here's a quick video illustrating the issue. 

http://www.screencast.com/t/eSIQ7uDSGWy

**Comment by melchoyce** [comment]
So, looking at this, it's not really a "bug" — since the header image only shows on the static front page template — but it's not _intuitive_, so I think we should change it. 

@laurelfulford, what would you think about showing the custom header on the front page, regardless of whether your front page displays a static page or posts? So, if you have your front page set to show your posts, [it would look like this](https://cloud.githubusercontent.com/assets/2846578/19224469/b3e6df74-8e54-11e6-809b-f5ec4d7299b1.jpg).

**Comment by laurelfulford** [comment]
@melchoyce I think that sounds like a good option.

**Comment by mrjarbenne** [comment]
Thanks for that. I think because I was testing on the initial lodestar commit, I assumed it was a regression when further design changes occurred. I imagine my confusion might be similar to others, given how in previous default themes the header perpetuates across all post types and static pages. I appreciate all your work on this. The theme looks great.
