### ISSUE TITLE
Featured image sizes / size limits

### ISSUE THREAD

**Issue by mor10** [WordPress/twentyseventeen#15]
The design calls for full-bleed featured images. This poses some interesting challenges:
1. Should the images have a maximum display height? If so, how is increasing width handled in terms of cropping?
2. What happens when the author uploads an image that is narrower than the current viewport width?
3. What happens when the site is displayed on a very wide or zoomed out screen?

Some of this is squarely a design decision, some of it has to do with implementation.

**Comment by ryelle** [comment]
@melchoyce added notes from the slack chat on #4, which are different ways to approach the width issue:
1. Stretch image so it's always full-width regardless of quality
2. Center align, provide background color, and allow the image to scale only up to it's max width
3. Could we grab the most prominent color and use that to auto-fill the background color?
4. Alternately, center align, show the image on a while background, and add a border to the bottom of the image area

I've done 3 on a few personal projects, and there are a few ways to do it.

For [Umbra](https://themes.redradar.net/umbra/), I used [Tonesque](https://github.com/Automattic/jetpack/blob/master/_inc/lib/tonesque.php) from Jetpack (which relies on a [color class](https://github.com/Automattic/jetpack/blob/master/_inc/lib/class.color.php)) to control the color scheme on single posts. It's well tested by being in Jetpack, so that's a benefit. It works by sampling 5 pixels out of the image, and averaging their colors, which is surprisingly accurate. This also has a built-in function for the contrasting color (white or black), which we'll need for the overlay text.

The PHP approach in [Dominant Colors for Lazy-Loading Images](https://manu.ninja/dominant-colors-for-lazy-loading-images) uses ImageMagick to shrink the image to a manageable size, then blur the image to one color, and fetch that color. I put together [a quick proof-of-concept plugin](https://github.com/ryelle/image-colors) to see how it works, and to see if we could grab the contrasting color here, too. We can, it just means a little more code to write :) – as for this approach, I'm not sure how much we need to support non-ImageMagick servers.

There're also a few JS-based approaches. I've used [node-vibrant](https://www.npmjs.com/package/node-vibrant) in the past, which has an in-browser version as well. This generates a palette of up to 6 colors, and doesn't do the contrasting color, but it does run fairly fast ([an example of vibrant](https://cloudup.com/cHYtabnqeGT)). [Dominant Colors for Lazy-Loading Images](https://manu.ninja/dominant-colors-for-lazy-loading-images) uses a different node package, not sure if it has a browser version. 

The JS versions would need to wait until the image loads, and would need to recalculate on each page reload. Vibrant runs quickly for me, but I'm on a fast computer. Personally, I like the ImageMagick solution, and (as in the plugin) it could be cached in post meta on the attachment (which would work for a site header too).

**Comment by mor10** [comment]
I would say option 1 (stretch images) is a non-starter for two reasons: a) it will look awful when people upload tiny images (they always do), and b) it would require some form of on-the-fly cropping of the image through JS or CSS, both of which are not clean.

I also have some reservations about the dominant background color ideas, primarily because it might end up looking either random, inconsistent, or just plain wrong. However, this is an opinion without empirical backing so I suggest we put together a demo to see exactly what happens when people upload images with unexpected colors.

**Comment by ryelle** [comment]
@mor10 what do you consider "images with unexpected colors"? I'm happy to upload a working concept, and could use edge-case images if you have any 😀 — I will admit the background color does fail a little on images that have their own borders, but I _think_ that's rare, and even then it doesn't look bad (in my opinion).

**Comment by melchoyce** [comment]
I'm interested in seeing a demo once more of the theme design is in place 👍

**Comment by Lorti** [comment]
> Dominant Colors for Lazy-Loading Images uses a different node package, not sure if it has a browser version.

gm is a just node.js wrapper around GraphicsMagick/ImageMagick.
Also if you need a palette via ImageMagick you should be able to quantize to X colors and then get the histogram via `Imagick::getImageHistogram()`. Haven't tried it, though.

**Comment by celloexpressions** [comment]
I'll note that a _lot_ of servers don't support ImageMagick, I believe the number was around 75% when support was first added in core 3-4 years ago. The numbers should be much better now, but still nowhere near where we'd need them for this to work without a really good fallback plan. I actually switched hosts when I needed it because I really needed it (see also ), but we obviously can't ask users to do that for this.

**Comment by josephfusco** [comment]
To avoid ImageMagick and js overhead all together, we could do something like this. (see below)

Because we are loading the same unchanged image twice, there will only be one network request as the second image would be served from the browser cache (as long as cache headers aren't set to no-cache). The backgrounds here would not be seen until the screen size was wider than the image's width. Exact implementation will have to wait until more of the design rolls out.

> 4. Alternately, center align, show the image on a white background, and add a border to the bottom of the image area

^ I think this is the cleanest approach though.

### blur applied

Applying a blur to help hide the poor image quality from being stretched.

![example-1](https://cloud.githubusercontent.com/assets/6676674/18972256/746f9c3c-8666-11e6-9a40-846266684dd4.jpg)

### opacity (no blur) with dark background

![example-2](https://cloud.githubusercontent.com/assets/6676674/18972882/e5b07220-8668-11e6-8d62-c7b4a61e4ad4.jpg)

### opacity (no blur) with light background

![example-3](https://cloud.githubusercontent.com/assets/6676674/18972883/e5b0da4e-8668-11e6-9ccb-79212f4aba45.jpg)

**Comment by celloexpressions** [comment]
Coincidentally, I was also just working on a blur approach :) In my case, I was thinking about repeating and transforming the image as opposed to stretching the transformed version. Here are a couple of generic examples I had mocked up:

![full-bleed-image-duplicate-blurred-cropped](https://cloud.githubusercontent.com/assets/7875961/18973380/0e7371b0-8652-11e6-9d69-e3a17b004ae1.jpg)

![full-bleed-heavy-blur](https://cloud.githubusercontent.com/assets/7875961/18973394/16349f14-8652-11e6-93d1-8a926ea09ce8.JPG)

This is fairly easy to do with CSS as `:before` and `:after` on the image _container_, using something loosely along the lines of (for the second example):

``` css
.entry-thumbnail:before, .entry-thumbnail:after {
    position: absolute;
    top: 0;
    content: url(file.jpg); /* this can probably read from a data-attribute on the container */
    left: calc(-100% + 25px);
    transform: rotateY(180deg);
    filter: blur(24px);
    z-index: -1;
}

.entry-thumbnail:after {
    left: calc(100% - 25px);
}
```

Re-using the image directly like this adds visual interest over a solid background color, and can also make it read better as one unified object, particularly if the edges of the actual image are soften to ease the transition.

**Comment by melchoyce** [comment]
I find the blur makes it super hard for me to focus on the actual image — it's very distracting. Thinking we should avoid that effect.

**Comment by mor10** [comment]
I understand the thinking with the background images, and in some cases it can look cool, but for most scenarios it'll be quite distracting. These techniques also rely heavily on poorly supported cutting edge CSS functionality meaning a lot of users will just see the image duplicated, something that will appear as an error.

IMO the best solution is to have a solid color background.

**Comment by celloexpressions** [comment]
For what it's worth, the version I mocked up doesn't use background images, it uses pseudo-elements. All major browsers now support the necessary properties without prefixing and we can prefix to support recent versions as well. The biggest compatibility issue would be IE, but Edge supports blur and we could stack the properties in a way that the fallback reduces to the single, original image.

If distracting from the image itself is a concern, I would lean more toward sticking with the surrounding background color (white) or a common theme-defined color rather than generating something to align with individual images. If the goal is more with the way the design reads visually with the image as a defining block in the page, then something like what's been discussed above would make more sense. My interpretation of the design is for the images to feel more atmospheric as design elements as opposed to being read more specifically as content to be focused on in its own right.

**Comment by mor10** [comment]
I was referring to CSS filters like blur etc.

To the second paragraph, it's relevant to consider how people use featured images. They are generally used to show an image directly related to or representative of the post in question, and is often used mainly to ensure an image is attachedto social sharing. In such cases, the idea of an "atmospheric" display is counter to the actual use.

Fwiw I still think the best solution is a plain background with a solid color defined by the theme or possibly controlled through the Customizer.

**Comment by josephfusco** [comment]
You can deff achieve a cross browser blur effect with a combo of stacked css filter properties and an inline SVG using `<feGaussianBlur>`. But I agree now, it is kind of distracting and taking away from the design.

+1 from me for using just a solid white as the background behind the featured image, or whatever the color scheme background is from customizer.

**Comment by melchoyce** [comment]
Thinking we should add a border between the featured image and the content area and set the background to match the header background color, like so:

![screen shot 2016-10-05 at 10 21 49 pm](https://cloud.githubusercontent.com/assets/2846578/19138517/e12072c8-8b4a-11e6-89b1-03b6b87aacc9.png)

**Comment by celloexpressions** [comment]
That seems like the best approach to me.
