### ISSUE TITLE
Linked image in footer widgets has underline.

### ISSUE THREAD

**Issue by sixhours** [WordPress/twentyseventeen#164]
https://cloudup.com/ijzlfdhLGGf

I'm using the Monster widget in the footer widget area.

**Comment by davidakennedy** [comment]
Somewhat related to the #133 and better gallery styles.

**Comment by tsl143** [comment]
I am a newbie to this, can someone help me to reproduce this?

**Comment by melchoyce** [comment]
@tsl143 — if you add an image into a text widget and wrap it in a link, the image has an underline.

I think this might be a problem for all linked images. We should look at it globally.

**Comment by jordesign** [comment]
Yeah - the underline is applied to a lot of `a` instance.
`
.entry-content a,
.entry-content a:visited,
.entry-summary a,
.entry-summary a:visited,
.widget a,
.widget a:visited,
.site-footer .widget-area a,
.site-footer .widget-area a:visited,
.posts-navigation a,
.posts-navigation a:visited,
.widget_authors a strong,
.widget_authors a:visited strong
`

based on that selector - we'd need to overide the style specifically on instances which contain an image - which could be pretty tricky.

**Comment by jordesign** [comment]
Looks like the underline is being applied to any anchor within the content or footer area. Perhaps if we make the style more specific ?
`p > a, h1 > 1, h2 > a` etc?

**Comment by melchoyce** [comment]
PR started here: #234

**Comment by melchoyce** [comment]
Sorry about the labeling, I got some PRs confused.

@laurelfulford Can you chime in here?

**Comment by laurelfulford** [comment]
> Perhaps if we make the style more specific ?

Unfortunately, it looks like the editor automatically includes the `p` tag around images in the content - even if they're on a new line 😞 

![Image](https://cldup.com/3mqaM08QO1.thumb.jpg)

The issue doesn't seem to be visible when the image is floated in the content area, just when it has no alignment. 

This _is_ tricky! I'll experiment with this and see if I can figure something out.

**Comment by tsl143** [comment]
@melchoyce , kindly review the PR if this fixes the issue, thanks :)

**Comment by laurelfulford** [comment]
Doing something like this could work in IE9 and up, ~~_except_ that it doesn't play nicely with background images:~~

```
.entry-content a img,
.widget a img {
    background: #fff;
    box-shadow: 0 0 0 6px #fff;
}
```

Putting it out there in case it inspires something more flexible and useable 🙂 

Note: we don't need to worry about the background if we go with one of the other hover options being discussed in #240.

Edited to add: Background images are also not an issue due to #135. So something like this could technically work if it could be tweaked include IE8 support. Open to other suggestions, too!

**Comment by joshcummingsdesign** [comment]
@laurelfulford To be honest with you, this solution looks good to me. IE8 has extremely low usage statistics and it actually doesn't look that bad in IE8. Not sure of any other way around this without JavaScript.

**Comment by melchoyce** [comment]
Can someone add an IE8 screenshot, for reference?

**Comment by laurelfulford** [comment]
Sure! It looks like this normally in IE8, even with the above fix:

![Image](https://cldup.com/6Z-aAHsX5y-3000x3000.png)

... and like this on hover:

![Image](https://cldup.com/4zHXt7BAQ2.thumb.jpg)

The hover will only look like that if the grey background is kept on hover. Otherwise, the bottom border will do... whatever the bottom border will do on hover 🙂 

All linked images in the content and widgets that are not floated left or right will look like this. Floating the image will 'hide' the border.

**Comment by laurelfulford** [comment]
Oh! It looks like we could add the following to the ie8.css:

```
.entry-content a img,
.widget a img {
    filter: progid:DXImageTransform.Microsoft.DropShadow(OffX=0, OffY=5, Color=#ffffff);
}
```

Then we get this in IE8:

![Image](https://cldup.com/5RYzLXXlcJ.thumb.jpg)

I didn't think to look up an IE8 work around before!

**Comment by joshcummingsdesign** [comment]
@laurelfulford This looks great! Even in IE8 it looks good.
![screen shot 2016-10-13 at 12 16 00 pm](https://cloud.githubusercontent.com/assets/11913201/19364028/5307cf02-9141-11e6-9988-dcd14f470d3c.png)
![screen shot 2016-10-13 at 12 18 35 pm](https://cloud.githubusercontent.com/assets/11913201/19364027/53070040-9141-11e6-90c9-89749915c181.png)

Updated in #285
