### ISSUE TITLE
Make a lighweight looking theme not heavy performance-wise

### ISSUE THREAD

**Issue by hostz-frank** [WordPress/twentyseventeen#174]
There are a lot of similar methods used in theme "2017" compared to "2016". And these are not the best ones if you take performance considerations into account. Why not - just for a change - with "2017" offer a "High Performance Website" theme as WordPress default theme?
1. "Above the fold" content should NOT be dependent on Javascript **before** something useful is already displayed to the user. Late-loading Javascript is best practice to achieve a minimum of network round trips and make browser rendering fast. Thats why the "2017" menu handling is - like in "2016" - **not as performant as it could be**. Solution: instead of toggling the mobile menu by Javascript I suggest using the "target" selector of CSS3. This is the most elegant way to toggle a menu without any JS dependencies.
2. Genericons. For 1 to maybe 5 used icons (meaning: "letters") in the content "above the fold" you make the theme dependent on an additional font. This and it's CSS have to be loaded **before** any content can be displayed. But the CSS will to 100% not be used, because you're even not using the CSS classes of Genericons but it's letters itself. So why are they loaded? We have a lot of cost performance-wise and almost no visual effect except more delay :-( Solution: make a subset of Genericons to what is really needed and avoid loading its CSS. Include this minimalistic font base64 encoded in the head of HTML, since the mobile menu is probably always present - even if the search bar will not be used.
3. Keep CSS as minimalistic as possible. Consider a more modular approach to split it up into context sensitive files and load these files dependently (e.g. a widget.css could only be loaded then if we're not in full width mode).
4. Consider finally to recommend a plugin like Autoptimize to gain full 100 points of Google's tool "Pagespeed Insights". Ideally the "insert all CSS in head" could be checked and the complete document's weight is gzipped not more than 14,6 kB (for one roud trip) even not, if a blog page is filled with content.

I know: if you install some plugins all of the initial speed is gone - but this is up to admin's choice and there are ways around that. The theme itself should provide the best and most performant starting point. **"2016" does not.** I know it because I took it to the [100 points level](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fdemo.conbrio.at%2F). Looking at [that site](http://demo.conbrio.at/) on a mobile phone you see a jumping menu. This is, because "2016" shows the mobile menu expanded when JS is not present. Then, when present (after late loading JS), it collapses the menu. This is really ugly ... but who in the world is in a mood to rebuild menu mechanics just for a bit more performance? You see the bloated CSS in head? This should really be done differently by smart themers, I guess.

So I would love to see themers performance aware. Maybe "2017" is the chance to come up with the first "High Performance Website" theme in the history of WP. Whooo!

**Comment by davidakennedy** [comment]
@hostz-frank Thanks for this thoughtful issue!

You're right, performance is important. You've put forth a lot of good ideas, many of which are touched on in other tickets:
- Overall performance: #9.
- Icon fonts, Twenty Seventeen may ditch them for SVGs: #60.
- Keeping CSS minimalistic, a CSS review ticket to help make sure things are clean: #12.

If you have specific thoughts on those tickets and the ideas within them, please comment there. I'd love to have more thoughts!

Regarding the menu idea with the `:target` selector, I'd have to see a pull request to test it out. I'm familiar with the technique, but default themes have a pretty wide level of browser support so it might be tough.

With recommending plugins, default themes generally do not do that because it's not fair to all the awesome plugins within the WordPress community that couldn't be recommended.

Some of this is tough to accomplish in a default theme. The more cutting-edge it gets sometimes means it's harder to understand. And default themes aren't just themes, but a learning tool for those new to WordPress and the Web. So it's a balance. 😄 

Thanks again for all these great thoughts. Please add anything to the relevant issues. I'm going to close this in favor of those other issues. I'd also suggest that creating issues that focus on one topic or bug is easier to handle for those contributing tot the project.
