### ISSUE TITLE
WooCommerce Supported

### ISSUE THREAD

**Issue by seb86** [WordPress/twentyseventeen#18]
Just a few things that I spotted that needs to be tweaked to support WooCommerce.
- [ ] Sidebar needs removing on shop archive and single product page.
- [ ] WooCommerce shop archive and single product page needs to be in a container.

**Comment by celloexpressions** [comment]
I don't think it's appropriate for a default theme to specifically support particular plugins. However, it would be good if we can make improvements with the way that things like the issues noted above work so that many popular plugins work well, and those plugins can add special support for bundled themes where needed as has been the practice in the past.

**Comment by seb86** [comment]
I thought that since WooCommerce is now part of Automattic that you would support WooCommerce in your core themes from now on like you do with JetPack.

**Comment by grappler** [comment]
The core themes are not part of Automattic. If it was an Automattic theme it would be in the their GitHub Org and not the WordPress.org GitHub profile.

**Comment by davidakennedy** [comment]
@seb86 Thanks for the feedback!

As others have mentioned, default themes typically do not support any plugins in specific ways because it wouldn't be fair to all the awesome plugins out there that a default theme couldn't support.

That said, if there are things that could be done to Twenty Seventeen that would make it easier for others to support WooCommerce (or other plugins) in a child theme or fork, I'd be open to hearing them. Let me know here what those are. Thanks again!

**Comment by mtomas7** [comment]
@seb86 Hi, can you point me to resources that outline WooCommerce compatibility for themes?

Thank you!

**Comment by seb86** [comment]
This should give you a head start.

https://docs.woocommerce.com/document/declare-woocommerce-support-in-third-party-theme/
https://docs.woocommerce.com/document/disable-the-default-stylesheet/
https://docs.woocommerce.com/document/third-party-custom-theme-compatibility/

**Comment by SilentComics** [comment]
Maybe it works the other way around. For instance, like how WooCommerce is set to work by default on Twenty Twelve.

**Comment by gorgoglionemeister** [comment]
I think these recently created [Woocommerce issue](https://github.com/woocommerce/woocommerce/issues/12038) and [branch](https://github.com/woocommerce/woocommerce/tree/add/twentyseventeen-support) are interesting for the discussion.

**Comment by davidakennedy** [comment]
It looks like WooCommerce Core is adding support for Twenty Seventeen and has added support for past default themes. So I'm going to close this issue, and would point people interested in this to WooCommerce.
