### ISSUE TITLE
Custom Post Type posts need padding on blog and archive pages

### ISSUE THREAD

**Issue by joyously** [WordPress/twentyseventeen#208]
`.blog .post, .archive .post, .search .hentry {
    padding-bottom: 4em;
}`
With this style, only the "Post" type is targeted, and custom post types have no padding.

**Comment by joyously** [comment]
It also looks like this rule is in style.css twice. Once with 2em around line 1480 and again with 4em around line 3095.

**Comment by melchoyce** [comment]
Thanks @joyously. Can you add a screenshot for visual reference?

**Comment by joyously** [comment]
The post with the blue image is a standard post. The three following are various custom post types.  
Ignore the menu that looks like it is right above the last post. I was scrolled down to there when I took the screenshot.
![custom-post-padding](https://cloud.githubusercontent.com/assets/7957680/19226037/882f0c46-8e6b-11e6-9237-dd03fbf09e4c.jpg)

**Comment by davidakennedy** [comment]
The reason for this is because `.hentry` is a class meant for search engines and is part of the [Microformats spec](http://microformats.org/wiki/hentry). So I think originally we set out not to style it. But being that it's the only class in Core part of [post_class](https://codex.wordpress.org/Function_Reference/post_class) that applies to all post types, it's been styled a lot in thousands of themes.

We should remove styles for `.hentry` and find another way to style. Hopefully, it can account for custom post types. See:

https://core.trac.wordpress.org/ticket/35978
And : https://github.com/WordPress/twentysixteen/pull/210

We should Twenty Sixteen's lead:

Use `.site-main > article` as a replacement of `hentry`.
