### ISSUE TITLE
Widget locations

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#229]
Hey

I just checked out the theme and am very impressed with all the work that has been done.
I did not notice an issue in regards to widget locations, so I thought I would start one.

Included widget locations are sidebar, footer 1 and footer 2.
Thoughts on additional widget locations?

I for one think it might be nice to include an after entry widget locations for displaying related posts, or whatever else that might have relevance to the reader of the post.

**Comment by joyously** [comment]
I figured there should be one in the content area of the front page, so that making "sections" could be easier. Instead of focusing on a new UI for that, we should just get better default widgets into core. One for a post list with thumbnails, one for a taxonomy with an image, one for Pages with an image...

**Comment by melchoyce** [comment]
Hi @paaljoachim, thanks for the suggesting.

The examples you're providing sound more like things that should be handled by plugins. 

Right now we don't have any plans on adding more widgets to Twenty Seventeen, so I'm going to close out this issue.

If you have more ideas, please continue making issues. :)

**Comment by paaljoachim** [comment]
Hey Mel..:)

It is easy enough to add new widgets in a Twenty Seventeen child theme.
This theme is coming along nicely and I look forward to creating tutorials on it in the future.
