### ISSUE TITLE
Author box?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentyseventeen#248]
I did not notice an author box.
It would be nice to have something like this:

![custom-authorbox-wordpress](https://cloud.githubusercontent.com/assets/5323259/19257713/c67e9488-8f3f-11e6-94d7-8dbdc62a1780.jpg)

Image from: http://easywebdesigntutorials.com/create-your-own-author-bio-box-in-wordpress-without-a-plugin/

**Comment by melchoyce** [comment]
Would love to hear opinions from folks who build websites for businesses here.

**Comment by joyously** [comment]
I think there are some small businesses that use this to their benefit. It's also good for multi-author blogs.
But if the focus is on business, instead of having an author box at the bottom of an individual post, you could have something similar at the top of the author archive page instead. 
If you do include it, it's always nice to be able to turn it off.

**Comment by hugobaeta** [comment]
> If you do include it, it's always nice to be able to turn it off.

I agree. I can even see a case for companies not wanting to make the author visible at all.

**Comment by davidakennedy** [comment]
Good issue to bring up for discussion @paaljoachim!

I don't want to add an option to hide it or display it for simplicity sake. Since this pattern was prominent in the last two default themes, both of which were more blogging focused, I'm in favor of leaving this off. I think that makes sense given the theme's focus on business sites.
