### ISSUE TITLE
Gallery and video post formats and featured images

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#258]
On the blog index and archive, the gallery post format will show both the first gallery from the post, and the featured image (if it exists):

![Image](https://cldup.com/AYCs2zdbFi-3000x3000.png)

If there is no gallery in the post content, the regular content is displayed instead. It seems like the featured image should only be shown in this fallback view, so the focus can be on the gallery.

The video post format does the same thing - it will display both the first video and featured image on the blog index.

![Image](https://cldup.com/FVvqDul4yZ.thumb.jpg)

Both should be updated to only show the featured image on the blog index if there is no gallery in the gallery post format, or no video in the video post format.

**Comment by joyously** [comment]
related to #190 and I sort of mentioned this in a [comment](https://github.com/WordPress/twentyseventeen/issues/133#issuecomment-252383825) 
I expected to see the words(content), if there are any, on list pages where all the other posts are showing full content. Otherwise, it seems like they should all show excerpts, for consistency.

**Comment by davidakennedy** [comment]
I think this makes sense to do @laurelfulford.

**Comment by enodekciw** [comment]
#300 should do the job :)

**Comment by laurelfulford** [comment]
Thanks @enodekciw!
