### ISSUE TITLE
Add IE8 fallback for SVGs

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#347]
IE8 doesn't support SVGs, so we need to add some fallbacks.

Depending on the icon, we can either replace it with text (by displaying the `screen-reader-text`) or an image fallback.

**Comment by samikeijonen** [comment]
I'd say we could show text at least on social menu. What do you think?

When I generated SVG icons in Icomoon, it also generated PNG files. Only problem with those are that they are always black. Or same color.

I haven't used PNG fallback myself so I need to look into this more deeply.

**Comment by samikeijonen** [comment]
@laurelfulford could you also add `svg` label for all SVG related issues, thanks.

**Comment by celloexpressions** [comment]
I don't think it's worth bundling extra files with the theme for IE8 fallbacks. So let's try to go text-only. The theme should work here, but it doesn't need to look great.

**Comment by samikeijonen** [comment]
> I don't think it's worth bundling extra files with the theme for IE8 fallbacks. So let's try to go text-only. The theme should work here, but it doesn't need to look great.

+10. For some cases text could break the layout or look strange. For example in front page Scroll down text.

For some cases there is no `screen-reader-text` within the icon. Like in sticky post icon. But that's not going to break the theme in IE8 even if there is no icon or any text.

I can create PR for text only fallback.

**Comment by davidakennedy** [comment]
Thanks for the pull request, @samikeijonen!

I'd like to see if using an `<img>` fallback within inline SVG would work. It's [highlighted here](https://css-tricks.com/a-complete-guide-to-svg-fallbacks/).

That way, the theme handles not just IE 8, but any browser that does not support SVGs. It's worth bundling extra images in that case.

**Comment by samikeijonen** [comment]
I can check that tomorrow.

**Comment by samikeijonen** [comment]
PR #381 have basic PNG fallback for SVGs. I'm not the biggest fun of this solution for couple of reasons.
1. PNGs doesn't look very good.
2. It has color contrast issues because it's really hard to maintain PNGs in different colors. See screenshot below.
3. It's not child theme friendly because you can't easily change PNG colors.
4. I don't know are the PNG images loaded even if they are not needed.

![fallback-png](https://cloud.githubusercontent.com/assets/1820415/19416664/5be65aa2-939f-11e6-85c1-73a263f4a3ae.png)

**Comment by joyously** [comment]
Why would you put the background color into the PNG? The image should be transparent and use the theme color for background-color behind it. That's why you use PNG and not JPG.

**Comment by samikeijonen** [comment]
> Why would you put the background color into the PNG?

Because I don't have control over PNGs when they are generated in Icomoon. Or maybe I do but I just don't know about it. Do you know how we can control generated PNGs?

Also PNGs have transparent color but the icon itself is solid color like `#000` at the moment. I think we can change that in Icomoon but that doesn't solve the problem.

**Comment by celloexpressions** [comment]
At a minimum, we'd need icons for the light and dark color schemes. I still don't think that there's enough use of non-supported browsers to justify adding these, and [IE8 is the only one listed on caniuse.com](http://caniuse.com/#search=svg).
