### ISSUE TITLE
Implement Twenty Seventeen's design fully

### ISSUE THREAD

**Issue by laurelfulford** [WordPress/twentyseventeen#4]
Twenty Seventeen is a fork of a yet-to-be-launched theme, Lodestar. Right now, the styles in GitHub reflect that original theme. The styles need to be updated to match Twenty Seventeen's design here:

https://cloudup.com/cR_df4xfeeG

**Comment by juanfra** [comment]
It'd be great to have the psd/sketch files. That way we will be able to rely on the different properties and dimensions colors/sizes/line-heights/everything. 

Is there any chance @melchoyce can make those available?

**Comment by WPDevHQ** [comment]
Would like this too.

Or at least the dimensions and image resourses used. I've started working on the header desing and the images would help visualize the intended final result better.

This is what I have so far...
![twentyseventeenheader](https://cloud.githubusercontent.com/assets/16872407/18412815/4589d778-7790-11e6-9b6d-b15e9a202dfb.png)

**Comment by WPDevHQ** [comment]
Does anyone wants to take a look at this before I do PR?
First iterration on header design: https://github.com/WPDevHQ/twentyseventeen/tree/header-design

**Comment by melchoyce** [comment]
I'm working with @laurelfulford and @davidakennedy for now to finalize the design, which still has some elements to work out. Once we have a more solid base that's looking less like Lodestar and more like Twenty Seventeen, we'll open up the theme for more contributors to work on implementing design. For now, hold tight and keep an eye on this ticket.

**Comment by melchoyce** [comment]
Design notes from [Friday's meeting](https://wordpress.slack.com/archives/core-themes/p1473446347000163):
- Extremely wide screens + what happens to images that are not wide enough to be full-bleed? (#15) [@mor10] Options:
  - Stretch image so it's always full-width regardless of quality
  - Center align, provide background color, and allow the image to scale only up to it's max width [@mor10]
  - Could we grab the most prominent color and use that to auto-fill the background color?
    - https://manu.ninja/dominant-colors-for-lazy-loading-images
  - Alternately, center align, show the image on a while background, and add a border to the bottom of the image area
- Consider making sidebar sticky (need to think about how this will work if we do pull-quotes) [@acosmin]
- The thick grey underline on links can make letters with descenders hard to read because of the lower contrast between it and the font [@aaronjorbin]
- Style an author comment [@aaronjorbin]
- Color contrast [@davidakennedy] 
  - This should be done now
- Color schemes? [@samuelsidler]
  - Some default color schemes baked into the theme
  - Allow users to build their own color schemes based on 1-4 hand-picked colors [@celloexpressions](I think probably 2 max in this theme since it's so monochromatic)
- Consider adding post thumbnails to post nav [@acosmin]
