### ISSUE TITLE
Playlists don't render on blog/archive pages

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentyseventeen#429]
![screen shot 2016-10-17 at 4 35 48 pm](https://cloud.githubusercontent.com/assets/2846578/19454664/0991ec5a-9488-11e6-94b7-0b3e4a87aba6.png)

**Comment by davidakennedy** [comment]
@melchoyce I can't reproduce this. Are you seeing any kind of errors anywhere, like in the browser console.

**Comment by melchoyce** [comment]
Nope, not seeing any errors.

**Comment by melchoyce** [comment]
This is the output HTML for each playlist:

`<div class="entry-video"><video controls="controls" preload="none" width="678" height="381"></video></div>`

`<div class="entry-audio"><audio controls="controls" preload="none" width="678"></audio></div>`

**Comment by davidakennedy** [comment]
@melchoyce Any plugins active?

**Comment by melchoyce** [comment]
Only the Beta Tester plugin, but it's been buggy since before I installed it.

**Comment by davidakennedy** [comment]
Okay, I can reproduce – nice find @melchoyce!

This happens when:

You have a video or audio playlist in a video or audio post format. It doesn't happen when just inserting one video or audio file.

**Comment by laurelfulford** [comment]
The Audio and Video post formats use `get_media_embedded_in_content` to get the associated media. 

The function scoops up the `<audio>` and `<video>` tags, respectively. When you just have a straight up `audio` or `video` tag created from an `[audio]` or `[video]` shortcode, the src is included with the tag. 

If I'm reading the code right, with the playlists it looks like the src is not included in the `<audio>` or `<video>` - it's added later with JavaScript (I'm guessing there isn't a non-JavaScript fallback because the playlist wouldn't work without JavaScript anyway). Because of this, the `<audio>` or `<video>` tag that's moved to the blog index is empty.

I'm not sure what a good fix would be here 😕

**Comment by joyously** [comment]
Is that the same reason that gallery posts only show a gallery on the blog index page? My gallery post has some text and two galleries, but only the first gallery shows on the blog page. All the normal posts show full content. Why don't the other post formats do the same?

**Comment by celloexpressions** [comment]
This seems like a core bug with that function. On the other hand, it might take a container function to make it more generically strip out shortcodes as opposed to the actual content tags, and also assume that audio playlists qualify as audio. Such a function could also handle grabbing the first image in the content or grabbing the first gallery, and allow the preferred/desired type to be specified as a parameter. This could potentially be doable in the next week if someone familiar with the media component has time to work on it. Also reference https://developer.wordpress.org/reference/functions/get_media_embedded_in_content/ for the current approach.

I like the idea of only showing the media content for the post type on index pages, as that provides purpose for the post formats. But without core adjustments, I'm not sure if the theme can reasonably support playlists with this.

**Comment by joyously** [comment]
It is misleading for the blog index page to show full content on some posts and not others.  A visitor would not go to the single post pages for audio, video, or gallery posts because it looks like the full content is showing, since the other posts show full content. They should all be full or all be excerpts.

**Comment by karmatosed** [comment]
Moved to trac: https://core.trac.wordpress.org/ticket/38390
