### ISSUE TITLE
Call to undefined function twentyseventeen_is_frontpage() and widget menu missing

### ISSUE THREAD

**Issue by yogasukma** [WordPress/twentyseventeen#435]
**step to recreate**
1. download theme as zip
2. replacing my old twentyseventeen theme
3. open home page
4. it showing
`Fatal error: Call to undefined function twentyseventeen_is_frontpage() in /home/vagrant/web/core/wp-content/themes/twentyseventeen/components/header/header-image.php on line 16`

and i notice in the wp-admin, appearance > widget are not showing up too

**Comment by yogasukma** [comment]
i tried to install it on very fresh wordpress install, but it fail me. it showed that twenty seventeen need wordpress 4.7 and my installation just 4.6.1.

is there any trick to get 4.7? since i didn't see at wp.org

**Comment by davidakennedy** [comment]
Hey @ysupr!

This happened because you had a previous version of the theme activated, which did not require 4.7. That change was made very recently.

The theme now requires WordPress 4.7 because it uses new features only available there. To fix this:
1. Activate another theme.
2. Install the beta testing plugin and follow instructions here: https://make.wordpress.org/core/handbook/testing/beta/
3. Once you have 4.7 running, you can activate Twenty Seventeen.

Good luck and thank you for helping test the theme!
