### ISSUE TITLE
First post title displayed as page title

### ISSUE THREAD

**Issue by alaczek** [WordPress/twentyseventeen#437]
On a fresh install of WordPress, right after Twenty Seventeen activation, the blog index page displays first post title as the page title above the post:

![image](https://cloud.githubusercontent.com/assets/4550351/19460570/9601a2de-9528-11e6-9509-db12283865bf.png)

**Comment by laurelfulford** [comment]
This looks like it's because in this line:

`<h2 class="page-title"><?php echo get_the_title( get_option( 'page_for_posts' ) ); ?></h2>`

This bit `get_option( 'page_for_posts' )` doesn't return anything because there isn't a page for posts set. 

If you set a static front page, pick a page for posts, and undo it, that page for posts title will be remembered and returned in this spot going forward.

The design shows a title to the left on the blog index page when there's no sidebar widget. Does it make sense to have a field where users can set a title for this? cc @melchoyce

**Comment by melchoyce** [comment]
I wouldn't add an option — in this specific case, I'd hide the "page title" entirely.

**Comment by davidakennedy** [comment]
Yeah, no options. 😄  I think we can fix this with a more thorough check.

**Comment by melchoyce** [comment]
I misunderstood what was going on — removing "pr needed" for now while we work out a better solution.

**Comment by davidakennedy** [comment]
After some experimentation and thought, I think the best option here is to:
- fix the check so it works better.
- display some default text for when the front page is the posts page. Probably "Recent Posts" or "Posts" Maybe "Posts" since the title would show on all pages, like `/page/6/` and so on.
- see this like labeling sticky posts "Featured". I think a decision should be made vs. creating an option.
