### ISSUE TITLE
posts pagination instead of posts navigation

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentyseventeen#64]
Hi,

Based on the proposed scope of this new default theme (business, product showcase, ...) I would suggest to use the core function `the_posts_pagination()` instead of `the_posts_navigation()` in the template files index.php, archive.php and search.php. This would result in a slightly more professional navigation between pages of posts.

Similarly to the Twenty Sixteen theme.

**Comment by BharatKaravadra** [comment]
I do not see there being an issue in having both next/previous and also numbered pagination navigation

I feel that next and previous post navigation links together with the titles of the post help engage readers, and numbered page navigation provides a sense of the depth of content.

**Comment by LittleBigThing** [comment]
I'm proposing to use numbered navigation for the paged posts list (the blog page).
Do not confuse it with the navigation between posts using the core function `the_post_navigation()`. Of course there should be a navigation between different posts the WP way.

**Comment by BharatKaravadra** [comment]
Thank you for the clarification @LittleBigThing and I was proposing both types of navigation wherever navigation appears.
If this is found to being too much or not appropriate for different users, perhaps it may be useful to have the option to select one or the other or both types of navigation.

**Comment by LittleBigThing** [comment]
Thanks @BharatKaravadra.

The function `the_posts_pagination()` displays the next and previous links. However, it is not possible to display a post title since they link to lists of posts and not one post.
The post title can (and should) be displayed when using `the_post_navigation()` to navigate between single posts.

I don't think that giving the option of choosing between numbered paging and simple paging in a default theme is in line with the [WP philosophy](https://wordpress.org/about/philosophy/).

**Comment by mor10** [comment]
+100 for numbered pagination on index pages. The standard "previous/next posts" approach is not user friendly.

**Comment by melchoyce** [comment]
I don't know what the difference is between the two functions or the context for this question. Can you explain further?

**Comment by mor10** [comment]
@melchoyce

The standard [the_posts_navigation()](https://developer.wordpress.org/reference/functions/the_posts_navigation/) outputs two links: "Older Posts" and "Newer Posts" I believe.

The proposed [the_posts_pagination()](https://codex.wordpress.org/Function_Reference/the_posts_pagination) outputs a more comprehensive list of links looking something like this:

Previous - 1 - 2 - 3 ... 8 - 9 - Next

IMO proper pagination provides a better user experience because it tells the visitor where they are in the index and gives them a sense of how much content is available.

**Comment by LittleBigThing** [comment]
Indeed, thanks @mor10!

**Comment by melchoyce** [comment]
Okay, that makes sense. I designed some numbered pagination for search pages that could work well for this instead of newer/older post: 

<img width="732" alt="screen shot 2016-09-23 at 2 17 11 pm" src="https://cloud.githubusercontent.com/assets/2846578/18796691/7cb7c928-8198-11e6-808c-cf29b646fd77.png">

**Comment by LittleBigThing** [comment]
Nice, +1!

**Comment by mor10** [comment]
That'll work on indeed pages too. Same function. DRY FTW

**Comment by mor10** [comment]
Index pages.

**Comment by melchoyce** [comment]
Cool. I've updated the mockups in Zeplin for @laurelfulford to show the numbers pagination instead of `older/newer`. Gonna close this out.

(May as well also cross-reference #4 so it shows up there)
