### ISSUE TITLE
Theme needs a description

### ISSUE THREAD

**Issue by josephfusco** [WordPress/twentyseventeen#94]
We need an official description as [style.css](https://github.com/WordPress/twentyseventeen/blob/master/style.css#L6) and [README.md](https://github.com/WordPress/twentyseventeen/blob/master/README.md#description) both show none.

@melchoyce

**Comment by melchoyce** [comment]
Any good copywriters want to help out with this one?

We should talk about how it's a modern business theme with an interesting asymmetrical grid. We should also highlight the two big features, video headers and a multi-section homepage (which needs a better name...).

**Comment by lukecav** [comment]
Rough start.

Description: Twenty Seventeen is a modernized take on an ever-popular WordPress layout. This theme will work well for a business or a portfolio site. Twenty Seventeen will make your WordPress site look beautiful everywhere.

**Comment by celloexpressions** [comment]
We should probably avoid using "modern" or "modernized" again, since Twenty Sixteen uses that. What about this as a baseline:

Twenty Seventeen brings your site to life with header videos and large images. With a focus on business sites, it supports multiple sections on the front page as well as widgets, menus, a custom logo, and more. Make it your own with color schemes and post formats. Our default theme for 2017, it features an asymmetrical grid and works great in any language, for any abilities, and on any device.

Some key points above:
- Emphasize language, device, and accessibility support.
- Highlight new and existing core features that make it particularly great for business sites.
- Mention some of the other features it has (some things are still pending).
- Point out that it's the default theme for 2017, as past default themes do.
- Try to use specific terminology that explains what it tries to do, rather than buzzwords like "responsive" that carry essentially no meaning in terms of highlighting a particular theme's features..

**Comment by ianstewart** [comment]
> Make it your own …

Maybe combine this sentence with the previous? "With a strong focus on business sites and customization, it supports multiple sections on the front page as well as widgets, menus, a custom logo, color schemes, and elegant post formatting."

Caveat: "Make it your own" has become a pet peeve for theme descriptions for me. :P

**Comment by lukecav** [comment]
I agree with it not using so many marketing buzz words.

**Comment by celloexpressions** [comment]
I'd like to separately emphasize the more content/business-oriented features from the more subtle design/usability features. Here's an iteration:

**Twenty Seventeen brings your site to life with header videos and immersive featured images. With a focus on business sites, it supports multiple sections on the front page as well as widgets, navigation and social menus, a custom logo, and more. Personalize its asymmetrical grid with a custom color scheme and showcase your multimedia content with post formats. Our default theme for 2017 works great in any language, for any abilities, and on any device.**

A key accompaniment to the first line - "brings your site to life" - will be to ensure that the default header image and by extension the screenshot incorporate organic subject matter (see #119).

It's time to explicitly try to avoid all of the most commonly used theme description text/buzzwords. I ran an analysis of the most-used words in the top ~150 themes currently on the "popular" list on .org, aggregating their descriptions (the text file, with the number of occurrences, and the image were generated using different tools, so the results are bit different). We should avoid using these words as much as possible:

[wp.org-150-most-popular-themes-descriptions-analysis.txt](https://github.com/WordPress/twentyseventeen/files/526398/wp.org-150-most-popular-themes-descriptions-analysis.txt)
![wp org-150-most-popular-themes-descriptions-analysis](https://cloud.githubusercontent.com/assets/7875961/19339476/6d971b98-90d8-11e6-9d18-3f015774d72b.png)
[wp.org-150-popular-themes-descriptions-data.txt](https://github.com/WordPress/twentyseventeen/files/526412/wp.org-150-popular-themes-descriptions-data.txt)

**Comment by melchoyce** [comment]
> Twenty Seventeen brings your site to life with header videos and immersive featured images. With a focus on business sites, it supports multiple sections on the front page as well as widgets, navigation and social menus, a custom logo, and more. Personalize its asymmetrical grid with a custom color scheme and showcase your multimedia content with post formats. Our default theme for 2017 works great in any language, for any abilities, and on any device.

I like this a lot. Can we commit it and iterate in core?

**Comment by celloexpressions** [comment]
Thanks for making a PR @josephfusco. I'd like to swap out the word "supports" in the second sentence with "features," and also replace "custom logo" with "logo," but otherwise this is still reading pretty well to me. With those changes, there are no meaningful repeated words. For the most part we're avoiding the common words I found above where reasonable. I'd also like to replace "videos" with "video", I think.

> Twenty Seventeen brings your site to life with header video and immersive featured images. With a focus on business sites, it features multiple sections on the front page as well as widgets, navigation and social menus, a logo, and more. Personalize its asymmetrical grid with a custom color scheme and showcase your multimedia content with post formats. Our default theme for 2017 works great in any language, for any abilities, and on any device.

**Comment by joyously** [comment]
I have a problem with this part:

> it features multiple sections on the front page as well as widgets, navigation and social menus, a logo, and more.

It sounds like the theme is supplying widgets, when it is not. It also could be interpreted as having a featured place on the front page for widgets, which it does not. (it does have a sidebar, but big whoop) 
I also don't like to leave them guessing what the "more" is, since some of what is listed is really mundane.

**Comment by melchoyce** [comment]
Thanks everyone! Let's add make new issues for any language tweaks.
